import { useEffect, useMemo, useRef, useState, type ChangeEvent } from "react";
import { backdropForRegion, setRegionBackdrop, type AppearanceMode, type BackdropSpec, type BackgroundRegion, type ThemeSpec } from "../model";

export type ThemeChangePhase = "immediate" | "continuous" | "final";
interface Props { theme: ThemeSpec | null; mode: AppearanceMode; region: BackgroundRegion; drawerOpen: boolean; onClose: () => void; onRegionChange: (region: BackgroundRegion) => void; onChange: (theme: ThemeSpec, label: string, phase?: ThemeChangePhase) => void; onUpload: (file: File, region: BackgroundRegion) => Promise<void>; onRestore: () => void; }
const tokenNames: Record<string, string> = { "--dsw-alias-bg-base": "基础背景", "--dsw-alias-bg-layer-1": "一级表面", "--dsw-alias-bg-layer-2": "二级表面", "--dsw-alias-bg-layer-3": "三级表面", "--dsw-alias-brand-primary": "品牌强调", "--dsw-alias-label-primary": "主要文字", "--dsw-alias-label-secondary": "次要文字", "--dsw-alias-border-l1": "轻边框", "--dsw-alias-border-l2": "标准边框", "--dsw-alias-state-error-primary": "错误状态", "--dsw-alias-state-success-primary": "成功状态" };

export function Inspector({ theme, mode, region, drawerOpen, onClose, onRegionChange, onChange, onUpload, onRestore }: Props) {
  const [tab, setTab] = useState<"background" | "tokens" | "info">("background"); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState<string>(); const [tokenQuery, setTokenQuery] = useState("");
  const tokens = useMemo(() => Object.entries(theme?.appearance.tokens ?? {}).filter(([name]) => `${name} ${tokenNames[name] ?? ""}`.toLowerCase().includes(tokenQuery.toLowerCase())), [theme, tokenQuery]);
  if (!theme) return <aside id="inspector" tabIndex={-1} className={`panel inspector ${drawerOpen ? "is-open" : ""}`} aria-label="属性编辑器"><div className="panel-loading">正在载入属性…</div></aside>;
  const backdrop = backdropForRegion(theme, region); const imageBackdrop = backdrop.kind === "image" ? backdrop : null; const targetLabel = theme.appearance.regions.linked ? "整合区域" : region === "sidebar" ? "左侧栏" : "主工作区";
  const setBackdrop = (next: BackdropSpec, label: string, phase: ThemeChangePhase = "immediate") => onChange(setRegionBackdrop(theme, region, next), label, phase);
  const updateBackdrop = (patch: Partial<BackdropSpec>, label: string, phase: ThemeChangePhase = "immediate") => setBackdrop({ ...backdrop, ...patch } as BackdropSpec, label, phase);
  const switchKind = (kind: BackdropSpec["kind"]) => { if (kind === "image") return; const colors = backdrop.kind === "image" ? ["#151716", "#2b403c"] : [...backdrop.colors]; if (kind !== "solid" && colors.length < 2) colors.push("#2b403c"); setBackdrop({ kind, colors: kind === "solid" ? [colors[0]!] : colors, angle: backdrop.kind === "image" ? 135 : backdrop.angle, opacity: backdrop.opacity, blurPx: backdrop.blurPx }, "切换背景类型"); };
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setUploadError(undefined); try { await onUpload(file, region); } catch (error) { setUploadError(error instanceof Error ? error.message : "图片导入失败，请换一张 PNG、JPEG 或 WebP 图片。"); } finally { setUploading(false); event.target.value = ""; } };
  const tabs = ["background", "tokens", "info"] as const;
  const selectByKey = (event: React.KeyboardEvent<HTMLButtonElement>, current: typeof tabs[number]) => { const index = tabs.indexOf(current); const next = event.key === "ArrowRight" ? tabs[(index + 1) % tabs.length] : event.key === "ArrowLeft" ? tabs[(index + tabs.length - 1) % tabs.length] : null; if (!next) return; event.preventDefault(); setTab(next); document.getElementById(`inspector-tab-${next}`)?.focus(); };
  return <aside id="inspector" tabIndex={-1} className={`panel inspector ${drawerOpen ? "is-open" : ""}`} aria-label="属性编辑器">
    <div className="inspector-tabs" role="tablist" aria-label="属性分类">{(["background", "tokens", "info"] as const).map((item) => <button key={item} id={`inspector-tab-${item}`} role="tab" aria-selected={tab === item} aria-controls={`inspector-panel-${item}`} tabIndex={tab === item ? 0 : -1} onKeyDown={(event) => selectByKey(event, item)} onClick={() => setTab(item)}>{({ background: "背景", tokens: "颜色变量", info: "信息" })[item]}</button>)}</div>
    {tab === "background" && <div id="inspector-panel-background" className="inspector-scroll" role="tabpanel" aria-labelledby="inspector-tab-background">
      <section className="control-section region-scope"><div className="section-heading"><div><span className="eyebrow">EDIT TARGET</span><h3>正在调整：{targetLabel}</h3></div></div>{theme.appearance.regions.linked ? <p>“整合两区域”已开启。背景、图片和视觉处理会同时作用于左侧栏与主工作区。</p> : <div className="region-radio" role="radiogroup" aria-label="选择要调整的背景区域"><label><input type="radio" name="background-region" checked={region === "sidebar"} onChange={() => onRegionChange("sidebar")} />左侧栏</label><label><input type="radio" name="background-region" checked={region === "main"} onChange={() => onRegionChange("main")} />主工作区</label></div>}</section>
      <section className="control-section"><div className="section-heading"><h3>背景资源</h3><button type="button" disabled={backdrop.kind !== "image"} onClick={() => switchKind("solid")}>移除图片</button></div><label className={`upload-zone ${uploading ? "is-loading" : ""}`}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} disabled={uploading} /><span className="upload-glyph" aria-hidden="true">↥</span><strong>{uploading ? "正在验证并导入…" : `导入${targetLabel}背景图片`}</strong><small>PNG、JPEG 或 WebP · 最大 4MB · 本地校验，不上传云端</small></label>{uploadError && <p className="upload-error" role="alert">{uploadError}</p>}<div className="kind-grid" aria-label="背景类型">{(["solid", "linear-gradient", "radial-gradient", "image"] as const).map((kind) => <button key={kind} aria-pressed={backdrop.kind === kind} disabled={kind === "image" && backdrop.kind !== "image"} onClick={() => switchKind(kind)}>{({ solid: "纯色", "linear-gradient": "线性", "radial-gradient": "径向", image: "图片" })[kind]}</button>)}</div></section>
      {backdrop.kind !== "image" && <section className="control-section"><div className="section-heading"><h3>颜色与渐变</h3><button type="button" onClick={() => updateBackdrop({ colors: ["#151716", "#2b403c"] }, "恢复背景颜色")}>恢复</button></div>{backdrop.colors.map((color, index) => <label className="color-control" key={`${index}-${color}`}><span>{index === 0 ? "起始色" : `颜色 ${index + 1}`}</span><input type="color" value={normalizeColor(color)} onChange={(event) => { const colors = [...backdrop.colors]; colors[index] = event.target.value; updateBackdrop({ colors }, "修改背景颜色"); }} /><ColorText value={color} onCommit={(value) => { const colors = [...backdrop.colors]; colors[index] = value; updateBackdrop({ colors }, "修改背景颜色"); }} /></label>)}{backdrop.kind !== "solid" && <Range label="角度" value={backdrop.angle} min={0} max={360} suffix="°" onChange={(angle, phase) => updateBackdrop({ angle }, "修改渐变角度", phase)} />}</section>}
      {imageBackdrop && <section className="control-section"><div className="section-heading"><h3>图片适配</h3></div><label className="field"><span>适配方式</span><select value={imageBackdrop.fit} onChange={(event) => updateBackdrop({ fit: event.target.value as "cover" | "contain" | "fill" }, "修改图片适配")}><option value="cover">填充</option><option value="contain">完整显示</option><option value="fill">拉伸</option></select></label><Range label="横向位置" value={imageBackdrop.position.xPercent} min={0} max={100} suffix="%" onChange={(xPercent, phase) => updateBackdrop({ position: { ...imageBackdrop.position, xPercent } }, "修改背景位置", phase)} /><Range label="纵向位置" value={imageBackdrop.position.yPercent} min={0} max={100} suffix="%" onChange={(yPercent, phase) => updateBackdrop({ position: { ...imageBackdrop.position, yPercent } }, "修改背景位置", phase)} /><label className="color-control"><span>遮罩颜色</span><input type="color" value={normalizeColor(imageBackdrop.overlay.color)} onChange={(event) => updateBackdrop({ overlay: { ...imageBackdrop.overlay, color: event.target.value } }, "修改背景遮罩")} /><ColorText value={imageBackdrop.overlay.color} onCommit={(value) => updateBackdrop({ overlay: { ...imageBackdrop.overlay, color: value } }, "修改背景遮罩")} /></label><Range label="遮罩强度" value={Math.round(imageBackdrop.overlay.opacity * 100)} min={0} max={100} suffix="%" onChange={(value, phase) => updateBackdrop({ overlay: { ...imageBackdrop.overlay, opacity: value / 100 } }, "修改背景遮罩", phase)} /></section>}
      <section className="control-section"><div className="section-heading"><h3>视觉处理</h3></div><Range label="背景不透明度" value={Math.round(backdrop.opacity * 100)} min={10} max={100} suffix="%" onChange={(opacity, phase) => updateBackdrop({ opacity: opacity / 100 }, "修改背景不透明度", phase)} /><Range label="背景模糊" value={backdrop.blurPx} min={0} max={24} suffix="px" onChange={(blurPx, phase) => updateBackdrop({ blurPx }, "修改背景模糊", phase)} /><Range label="面板透明度" value={Math.round(theme.appearance.glass.opacity * 100)} min={20} max={100} suffix="%" onChange={(value, phase) => onChange({ ...theme, appearance: { ...theme.appearance, glass: { ...theme.appearance.glass, opacity: value / 100 } } }, "修改面板透明度", phase)} /></section>
    </div>}
    {tab === "tokens" && <div id="inspector-panel-tokens" className="inspector-scroll" role="tabpanel" aria-labelledby="inspector-tab-tokens"><div className="token-toolbar"><input value={tokenQuery} onChange={(event) => setTokenQuery(event.target.value)} placeholder="搜索变量或用途" /><span>{mode === "system" ? "当前显示两套值" : mode === "dark" ? "深色值" : "浅色值"}</span></div><div className="token-list">{tokens.map(([name, values]) => <div className="token-row" key={name}><div><strong>{tokenNames[name] ?? "主题变量"}</strong><code>{name}</code></div><div className="token-values">{(mode === "system" ? ["light", "dark"] : [mode]).map((key) => <label key={key}><span>{key === "dark" ? "深" : "浅"}</span><input type="color" value={normalizeColor(values[key as "light" | "dark"])} onChange={(event) => onChange({ ...theme, appearance: { ...theme.appearance, tokens: { ...theme.appearance.tokens, [name]: { ...values, [key]: event.target.value } } } }, `修改 ${tokenNames[name] ?? name}`)} /></label>)}</div></div>)}</div></div>}
    {tab === "info" && <div id="inspector-panel-info" className="inspector-scroll info-panel" role="tabpanel" aria-labelledby="inspector-tab-info"><span className="eyebrow">THEME SPEC</span><h3>{theme.name}</h3><dl><div><dt>Schema</dt><dd>v{theme.schemaVersion}</dd></div><div><dt>目标版本</dt><dd>DSH 0.1.0-rc.6</dd></div><div><dt>主题 ID</dt><dd><code>{theme.id}</code></dd></div><div><dt>区域模式</dt><dd>{theme.appearance.regions.linked ? "整合两区域" : "分别调整"}</dd></div><div><dt>当前目标</dt><dd>{targetLabel}</dd></div><div><dt>颜色变量</dt><dd>{Object.keys(theme.appearance.tokens).length}</dd></div></dl><button className="button button-recovery" type="button" onClick={onRestore}>恢复上一稳定外观</button></div>}
  </aside>;
}
function Range({ label, value, min, max, suffix, onChange }: { label: string; value: number; min: number; max: number; suffix: string; onChange: (value: number, phase: ThemeChangePhase) => void }) {
  const [draft, setDraft] = useState(value);
  const frame = useRef<number>();
  const queued = useRef(value);
  const interactionActive = useRef(false);
  useEffect(() => {
    if (interactionActive.current) return;
    setDraft(value);
    queued.current = value;
  }, [value]);
  useEffect(() => () => { if (frame.current !== undefined) cancelAnimationFrame(frame.current); }, []);
  const emitContinuous = (next: number) => {
    interactionActive.current = true;
    setDraft(next);
    queued.current = next;
    if (frame.current !== undefined) return;
    frame.current = requestAnimationFrame(() => {
      frame.current = undefined;
      onChange(queued.current, "continuous");
    });
  };
  const flush = (next: number) => {
    setDraft(next);
    queued.current = next;
    if (frame.current !== undefined) {
      cancelAnimationFrame(frame.current);
      frame.current = undefined;
    }
    if (!interactionActive.current) return;
    interactionActive.current = false;
    onChange(next, "final");
  };
  return <label className="range-control"><span>{label}</span><input type="range" min={min} max={max} value={draft} onChange={(event) => emitContinuous(Number(event.target.value))} onPointerUp={(event) => flush(Number(event.currentTarget.value))} onPointerCancel={(event) => flush(Number(event.currentTarget.value))} onKeyUp={(event) => flush(Number(event.currentTarget.value))} onBlur={(event) => flush(Number(event.currentTarget.value))} /><output>{draft}{suffix}</output></label>;
}
function ColorText({ value, onCommit }: { value: string; onCommit: (value: string) => void }) { const [draft, setDraft] = useState(value); useEffect(() => setDraft(value), [value]); const commit = () => { const next = draft.trim(); if (/^(#[0-9a-f]{3,8}|rgba?\([0-9.,%\s]+\)|hsla?\([0-9.,%\s]+\)|transparent|currentColor)$/i.test(next)) onCommit(next); else setDraft(value); }; return <input className="mono-input" value={draft} aria-invalid={draft !== value && !/^(#[0-9a-f]{3,8}|rgba?\([0-9.,%\s]+\)|hsla?\([0-9.,%\s]+\)|transparent|currentColor)$/i.test(draft.trim())} onChange={(event) => setDraft(event.target.value)} onBlur={commit} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); else if (event.key === "Escape") { setDraft(value); event.currentTarget.blur(); } }} />; }
function normalizeColor(value: string): string { return /^#[0-9a-f]{6}$/i.test(value) ? value : "#000000"; }
