import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { backdropForRegion, backgroundCssForBackdrop, type BackgroundRegion, type DesignSession, type PreviewSession, type PreviewState } from "../model";
import { RefreshIcon } from "./Icons";

interface Props { design: DesignSession | null; preview: PreviewState; verifiedSession: PreviewSession | null; candidateSession: PreviewSession | null; selectedRegion: BackgroundRegion; assetUrls?: Partial<Record<BackgroundRegion, string>>; onPreview: () => void; onRegionSelect: (region: BackgroundRegion) => void; onLinkedChange: (linked: boolean) => void; onDividerChange: (divider: boolean) => void; }
const stateLabel: Record<PreviewState, string> = { staging: "连接温预览", live: "隔离实时预览", updating: "复用温预览", expired: "预览已过期", error: "预览出错" };

export function PreviewWorkbench({ design, preview, verifiedSession, candidateSession, selectedRegion, assetUrls, onPreview, onRegionSelect, onLinkedChange, onDividerChange }: Props) {
  const [viewport, setViewport] = useState("auto"); const [frameLoaded, setFrameLoaded] = useState(false); const [frameHover, setFrameHover] = useState(false); const [stageSize, setStageSize] = useState({ width: 0, height: 0 });
  const stageRef = useRef<HTMLDivElement>(null); const frameRef = useRef<HTMLIFrameElement>(null);
  const visibleSession = useMemo(() => {
    // Switching designs kills the previous warm runner, so its verified frame
    // is a dead URL. Point the main frame at the new session's URL as soon as
    // it exists (and show the loading placeholder before that), instead of
    // keeping a dead frame on screen until the new session reaches live.
    const switchedDesign = Boolean(candidateSession && verifiedSession && candidateSession.designId !== verifiedSession.designId);
    if (switchedDesign) return candidateSession?.previewUrl ? candidateSession : null;
    return verifiedSession?.previewUrl ? verifiedSession : candidateSession?.previewUrl ? candidateSession : null;
  }, [candidateSession, verifiedSession]);
  const visibleUrl = visibleSession?.previewUrl ?? null;
  const linked = design?.theme.appearance.regions.linked ?? true;
  const divider = design?.theme.appearance.regions.divider ?? false;
  const visibleOrigin = useMemo(() => loopbackOrigin(visibleUrl), [visibleUrl]);
  const sendMode = useCallback(() => { if (!visibleOrigin || !frameRef.current?.contentWindow || !visibleSession) return; frameRef.current.contentWindow.postMessage({ type: "dsh-skin-region-mode", selectedRegion, linked, sessionId: visibleSession.sessionId, generation: visibleSession.generation }, visibleOrigin); }, [linked, selectedRegion, visibleOrigin, visibleSession]);
  useEffect(() => { setFrameLoaded(false); }, [visibleUrl]);
  useEffect(() => { if (!linked) setFrameHover(false); }, [linked]);
  useEffect(() => { const stage = stageRef.current; if (!stage) return; const update = () => { const style = getComputedStyle(stage); setStageSize({ width: Math.max(0, stage.clientWidth - Number.parseFloat(style.paddingLeft) - Number.parseFloat(style.paddingRight)), height: Math.max(0, stage.clientHeight - Number.parseFloat(style.paddingTop) - Number.parseFloat(style.paddingBottom)) }); }; update(); const observer = new ResizeObserver(update); observer.observe(stage); return () => observer.disconnect(); }, []);
  useEffect(() => { if (frameLoaded) sendMode(); }, [frameLoaded, sendMode]);
  useEffect(() => {
    const receive = (event: MessageEvent<unknown>) => {
      if (!visibleOrigin || event.origin !== visibleOrigin || event.source !== frameRef.current?.contentWindow || !visibleSession || !event.data || typeof event.data !== "object") return;
      const data = event.data as { type?: unknown; event?: unknown; value?: unknown; sessionId?: unknown; generation?: unknown; designId?: unknown; revision?: unknown };
      if (data.type !== "dsh-skin-region-bridge" || data.sessionId !== visibleSession.sessionId || data.generation !== visibleSession.generation || data.designId !== visibleSession.designId || data.revision !== visibleSession.revision) return;
      if (data.event === "region-select" && (data.value === "sidebar" || data.value === "main")) onRegionSelect(data.value);
      if (data.event === "regions-linked" && typeof data.value === "boolean") onLinkedChange(data.value);
    };
    window.addEventListener("message", receive); return () => window.removeEventListener("message", receive);
  }, [onLinkedChange, onRegionSelect, visibleOrigin, visibleSession]);
  const frameWidth = viewport === "auto" ? undefined : Number(viewport); const frameScale = frameWidth && stageSize.width ? Math.min(1, stageSize.width / frameWidth) : 1; const scaledHeight = Math.max(320, stageSize.height || 320); const fixedFrameStyle = frameWidth ? { width: `${frameWidth}px`, height: `${scaledHeight / frameScale}px`, transform: `scale(${frameScale})`, transformOrigin: "top left" } : undefined; const frameWrapperStyle = frameWidth ? { width: `${frameWidth * frameScale}px`, height: `${scaledHeight}px` } : undefined;
  const hasCandidateBehind = Boolean(verifiedSession && candidateSession?.previewUrl && candidateSession.previewUrl !== verifiedSession.previewUrl && preview !== "live");
  return <main id="preview-workbench" tabIndex={-1} className="preview-workbench" aria-label="隔离的 DeepSeek Harness 实时预览">
    <div className="preview-toolbar"><div className="scene-tabs" aria-label="预览场景"><button aria-pressed="true">会话</button><button disabled>首页</button><button disabled>设置</button></div><div className="preview-controls"><label className="regions-toggle"><input type="checkbox" checked={linked} onChange={(event) => onLinkedChange(event.target.checked)} /><span>整合两区域</span></label><label className="regions-toggle regions-divider"><input type="checkbox" checked={divider} onChange={(event) => onDividerChange(event.target.checked)} /><span>增加分隔线</span></label><label><span className="sr-only">预览视口</span><select value={viewport} onChange={(event) => setViewport(event.target.value)}><option value="auto">自适应</option><option value="1440">1440</option><option value="1024">1024</option><option value="390">390</option></select></label><button className="icon-button" type="button" aria-label="刷新温隔离预览" title="刷新温隔离预览" onClick={onPreview}><RefreshIcon /></button><span className={`preview-badge state-${preview}`}><i aria-hidden="true" />{stateLabel[preview]}</span></div></div>
    <div ref={stageRef} className="preview-stage"><div className="stage-grain" aria-hidden="true" /><div className="viewport-scale-shell" style={frameWrapperStyle}><div className="viewport-shell" style={fixedFrameStyle}><div className="viewport-chrome"><span /><span /><span /><strong>DeepSeek Harness · 隔离副本</strong><small>{frameWidth ? `${frameWidth}px · ${Math.round(frameScale * 100)}% · ` : ""}{design ? `r${design.revision}` : "—"}</small></div>{visibleUrl ? <div className="frame-wrap" onPointerEnter={() => { if (linked) setFrameHover(true); }} onPointerLeave={() => setFrameHover(false)}>{!frameLoaded && <div className="frame-loading" aria-live="polite"><span className="spinner" />正在加载隔离预览…</div>}<iframe ref={frameRef} title="隔离的 DeepSeek Harness 预览，不会写入我的 DSH" src={visibleUrl} onLoad={() => { setFrameLoaded(true); sendMode(); }} />{linked && frameHover && <div className="linked-preview-hover-frame" data-dsh-skin-linked-hover aria-hidden="true"><span>整合背景区域</span></div>}{hasCandidateBehind && candidateSession && <iframe className="preview-candidate-frame" aria-hidden="true" tabIndex={-1} title="隔离预览预热帧" src={candidateSession.previewUrl} />}{preview !== "live" && <div className="preview-truth-label">{verifiedSession ? "仍显示上一帧已确认预览；温实例正在验证新草稿" : "正在验证温隔离预览；尚未写入我的 DSH"}</div>}</div> : <OfflineCanvas />}</div></div><div className="preview-isolation-strip" role="status" aria-live="polite"><strong>真实隔离 DSH</strong><span>复用一个温实例；确认前不会修改你的 DSH。</span></div><DraftCanvas design={design} selectedRegion={selectedRegion} {...(assetUrls ? { assetUrls } : {})} onRegionSelect={onRegionSelect} />{(preview === "expired" || preview === "error") && <div className="preview-callout" role="alert"><strong>{preview === "expired" ? "隔离预览已过期" : "隔离预览未能建立"}</strong><span>可重新连接；已确认的上一帧会保留，且不会写入你的 DSH。</span><button className="button button-preview" type="button" onClick={onPreview}>重新连接</button></div>}</div>
  </main>;
}

function DraftCanvas({ design, selectedRegion, assetUrls, onRegionSelect }: { design: DesignSession | null; selectedRegion: BackgroundRegion; assetUrls?: Partial<Record<BackgroundRegion, string>>; onRegionSelect: (region: BackgroundRegion) => void }) {
  if (!design) return null; const { theme } = design; const linked = theme.appearance.regions.linked; const divider = theme.appearance.regions.divider; const token = theme.appearance.tokens; const foreground = token["--foreground"]?.[theme.appearance.base] ?? "#17211d"; const surface = token["--background"]?.[theme.appearance.base] ?? "#f4f7f4";
  const sample = (region: BackgroundRegion) => { const backdrop = backdropForRegion(theme, region); return { backgroundImage: backgroundCssForBackdrop(backdrop, assetUrls?.[region]), backgroundColor: backdrop.kind === "image" ? "#151716" : backdrop.colors[0], color: foreground, borderColor: surface } as CSSProperties; };
  const blended = !linked && !divider ? splitBlendCss(theme) : undefined;
  return <section className={`draft-canvas ${linked ? "is-linked" : "is-split"}`} aria-label="即时双区域草稿画布，尚未作为真实隔离 DSH 证据"><header><strong>即时草稿</strong><small>未验证</small></header><p>{linked ? divider ? "两区域共用一张背景画布，并显示分隔线。" : "两区域已整合，背景连续且没有分隔线。" : divider ? "分别调整两区域，并显示分隔线。" : "分别调整两区域，边界会柔和过渡。"}</p><div className={`draft-regions ${divider ? "has-divider" : "no-divider"}`} style={linked ? sample("main") : undefined}><button type="button" className={selectedRegion === "sidebar" ? "is-selected" : ""} aria-pressed={selectedRegion === "sidebar"} onClick={() => onRegionSelect("sidebar")} style={linked ? { background: "transparent", color: foreground } : sample("sidebar")}><span>左侧栏</span></button><button type="button" className={selectedRegion === "main" ? "is-selected" : ""} aria-pressed={selectedRegion === "main"} onClick={() => onRegionSelect("main")} style={linked ? { background: "transparent", color: foreground } : sample("main")}><span>主工作区</span></button>{blended && <i className="draft-region-blend" style={{ background: blended }} aria-hidden="true" />}</div></section>;
}
function splitBlendCss(theme: DesignSession["theme"]): string {
  const edge = (region: BackgroundRegion, side: "left" | "right") => { const backdrop = theme.appearance.regions[region]; if (backdrop.kind === "image") return backdrop.overlay.color; if (backdrop.kind === "solid") return backdrop.colors[0]!; return side === "left" ? backdrop.colors.at(-1)! : backdrop.colors[0]!; };
  const left = edge("sidebar", "left"), right = edge("main", "right");
  return `linear-gradient(90deg, color-mix(in srgb, ${left} 82%, transparent), color-mix(in srgb, ${left} 18%, transparent) 42%, color-mix(in srgb, ${right} 18%, transparent) 58%, color-mix(in srgb, ${right} 82%, transparent))`;
}
function OfflineCanvas() { return <div className="offline-canvas" aria-label="等待隔离预览的结构化皮肤画布"><nav><span className="mini-brand">deepseek</span><button>＋ 新对话</button><small>连接温隔离预览</small><i /><i /><i /></nav><section><header><span>温隔离预览准备中</span><small>不会写入 DSH</small></header><article><p>正在连接可复用的临时副本。你可以继续调整背景与主题变量。</p><div className="sample-message"><strong>Skin Studio</strong><span>确认渲染后，真实的隔离 DSH 页面会显示在这里。</span></div></article><footer><span>输入消息…</span><button>↑</button></footer></section></div>; }
function loopbackOrigin(value?: string | null): string | null { if (!value) return null; try { const url = new URL(value); return url.protocol === "http:" && ["127.0.0.1", "localhost", "::1"].includes(url.hostname) ? url.origin : null; } catch { return null; } }
